services:

  eth-node:
    container_name: geth-1.10
    ports: [ '8545:8545' ]
    image: ethereum/client-go:release-1.10
    command: --verbosity 1
      --http.vhosts '*,localhost,host.docker.internal'
      --http
      --http.api personal,eth,net,web3,debug
      --http.corsdomain '*'
      --http.addr "0.0.0.0"
      --networkid 1337
      --ignore-legacy-receipts
      --dev
      --dev.period 0
      --allow-insecure-unlock
      --rpc.allow-unprotected-txs
      --dev.gaslimit 20000000
      --mine
      --miner.threads 1
      --miner.gaslimit 12000000
