name: Build Dashboard

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push: 
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FORCE_COLORS: 1

jobs:

  runall:
    runs-on: ubuntu-latest

    steps:

      - run: pip install jq yq
      - run: curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -

      - run: echo $PATH; echo which pdm=`which pdm`
 
      - uses: actions/checkout@v1

      - uses: actions/checkout@v3
        with:
          repository: eth-infinitism/bundler-spec-tests
          ref: modules-https
          path: bundler-spec-tests
          submodules: true

      #cache the bundler-spect-tests folder, but rebuild on change to specs, contracts or python deps
      - uses: actions/cache@v2
        with:
          path: bundler-spec-tests
          key: ${{ runner.os }}-${{ hashFiles('bundler-spec-tests/pdm.lock', 'bundler-spec-tests/.git/modules/*/refs/heads/*') }}


      - run: "grep . bundler-spec-tests/.gitmodules bundler-spec-tests/.git/modules/*/refs/heads/*; env"
      - run: "cd bundler-spec-tests && pdm install && pdm update-deps"

      - run: ./runall.sh


