name: Build Dashboard

on: 
  workflow_dispatch:
  push: 
    branches:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FORCE_COLORS: 1

jobs:

  runall:
    runs-on: ubuntu-latest

    steps:

      - run: curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -

      - run: pip install jq yq

      - uses: actions/checkout@v1

      # - uses: actions/checkout@v3
      #   with:
      #     repository: eth-infinitism/bundler-spec-tests
      #     ref: modules-https
      #     path: bundler-spec-tests
      #     submodules: true

      - run: test -d bundler-spec-tests || git clone --recurse-submodules --depth 1 https://github.com/eth-infinitism/bundler-spec-tests -b modules-https && yarn --cwd bundler-spec-tests/spec remove gatsby

      - uses: actions/cache@v2
        with:
          path: bundler-spec-tests
          key: ${{ runner.os }}-${{ hashFiles('bundler-spec-tests/pdm.lock', 'bundler-spec-tests/.git/modules/*/refs/heads/*') }}

      - run: echo $PATH; echo which pdm=`which pdm`
 
      - run: "grep . bundler-spec-tests/.gitmodules bundler-spec-tests/.git/modules/*/refs/heads/*; env"
      - run: "cd bundler-spec-tests && pdm install && pdm update-deps"

      - run: ./runall.sh

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

